// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8soaTar970JO5VAvSB0RFvmPRDlle30',
    appId: '1:668374533230:web:f819c615deb634be2d927f',
    messagingSenderId: '668374533230',
    projectId: 'livestreamingap',
    authDomain: 'livestreamingap.firebaseapp.com',
    storageBucket: 'livestreamingap.appspot.com',
    measurementId: 'G-1X7HN26M06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4l33iPdLbesYX7x_Bm8lMQ5w9Di92Z3s',
    appId: '1:668374533230:android:3b3d2ed2a799dda12d927f',
    messagingSenderId: '668374533230',
    projectId: 'livestreamingap',
    storageBucket: 'livestreamingap.appspot.com',
  );
}
